### ISSUE TITLE
Failing build with Heroku deploy added to .travis.yml

### ISSUE THREAD

**Issue by nzey** [nzey/image_viewer#1]
Ran this in command line:
```
travis encrypt $(heroku auth:token) --add deploy.api_key
```

Which added this to .travis.yml:
```
deploy:
  provider: heroku
  api_key:
    secure: kcopF0/d6MHA...
```
Caused this build error:

<img width="787" alt="screen shot 2017-07-16 at 2 01 20 pm" src="https://user-images.githubusercontent.com/15035454/28251310-897a65d2-6a2f-11e7-9228-ea065ba4075c.png">
